queue_rules:
  - name: ansible-ai-connect-service
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    merge_conditions:
      - check-success=pre-commit
      - check-success=code_coverage
      - check-success=selftest

pull_request_rules:
  # Auto-approve security updates for Python
  - name: Auto-approve Dependabot security updates (Python)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=python
      - check-success=pre-commit
      - check-success=selftest  # pip_compile check
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      review:
        type: APPROVE
        message: "Dependabot security PR auto-approved. Manual merge required."

  # Auto-approve security updates for Admin Portal
  - name: Auto-approve Dependabot security updates (Admin Portal)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=admin-portal
      - check-success=pre-commit
      - check-success=npm_audit
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      review:
        type: APPROVE
        message: "Dependabot security PR auto-approved. Manual merge required."

  # Auto-approve security updates for Chatbot
  - name: Auto-approve Dependabot security updates (Chatbot)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=chatbot
      - check-success=pre-commit
      - check-success=npm_audit_chatbot
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      review:
        type: APPROVE
        message: "Dependabot security PR auto-approved. Manual merge required."

  # Auto-approve security updates for GitHub Actions
  - name: Auto-approve Dependabot security updates (GitHub Actions)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=github-actions
      - check-success=pre-commit
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      review:
        type: APPROVE
        message: "Dependabot security PR auto-approved. Manual merge required."

  # Auto-approve non-security updates but don't merge
  - name: Auto-approve non-security Dependabot PRs
    conditions:
      - author=dependabot[bot]
      - -label=security
      - check-success=pre-commit
      - check-success=selftest
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      review:
        type: APPROVE
        message: "Dependabot PR auto-approved. Manual merge required for non-security updates."
