queue_rules:
  - name: ansible-ai-connect-service-python-dep
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=python
    merge_conditions:
      - check-success=pre-commit
      - check-success=Unit Test and SonarCloud Scan
      - check-success=selftest

  - name: ansible-ai-connect-service-admin-portal
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=admin-portal
    merge_conditions:
      - check-success=pre-commit
      - check-success=Admin Portal - npm-audit / lint

  - name: ansible-ai-connect-service-chatbot
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=chatbot
    merge_conditions:
      - check-success=pre-commit
      - check-success=Chatbot - npm-audit / lint

  - name: ansible-ai-connect-service-github-actions
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=github-actions
    merge_conditions:
      - check-success=pre-commit

pull_request_rules:
  # Auto-merge security updates for Python
  - name: Auto-merge Dependabot security updates (Python)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=python
      - check-success=pre-commit
      - check-success=selftest  # pip_compile check
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service-python-dep

  # Auto-merge security updates for Admin Portal
  - name: Auto-merge Dependabot security updates (Admin Portal)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=admin-portal
      - check-success=pre-commit
      - check-success=Admin Portal - npm-audit / lint
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service-admin-portal

  # Auto-merge security updates for Chatbot
  - name: Auto-merge Dependabot security updates (Chatbot)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=chatbot
      - check-success=pre-commit
      - check-success=Chatbot - npm-audit / lint
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service-chatbot

  # Auto-merge security updates for GitHub Actions
  - name: Auto-merge Dependabot security updates (GitHub Actions)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=github-actions
      - check-success=pre-commit
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service-github-actions

  # Detect when PR conflicts and add label
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "This pull request is now in conflicts. Could you fix it @{{author}}?
          🙏"
      label:
        add:
          - conflict
