queue_rules:
  - name: ansible-ai-connect-service
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    merge_conditions:
      - check-success=pre-commit
      - check-success=code_coverage
      - check-success=selftest

pull_request_rules:
  # Auto-merge security updates for Python
  - name: Auto-merge Dependabot security updates (Python)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=python
      - check-success=pre-commit
      - check-success=selftest  # pip_compile check
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service

  # Auto-merge security updates for Admin Portal
  - name: Auto-merge Dependabot security updates (Admin Portal)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=admin-portal
      - check-success=pre-commit
      - check-success=npm_audit
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service

  # Auto-merge security updates for Chatbot
  - name: Auto-merge Dependabot security updates (Chatbot)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=chatbot
      - check-success=pre-commit
      - check-success=npm_audit_chatbot
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service

  # Auto-merge security updates for GitHub Actions
  - name: Auto-merge Dependabot security updates (GitHub Actions)
    conditions:
      - author=dependabot[bot]
      - label=security
      - label=github-actions
      - check-success=pre-commit
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service

  # Auto-merge non-security updates
  - name: Auto-merge non-security Dependabot PRs
    conditions:
      - author=dependabot[bot]
      - -label=security
      - check-success=pre-commit
      - check-success=selftest
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
    actions:
      queue:
        name: ansible-ai-connect-service

  # Detect when PR conflicts and add label
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "This pull request is now in conflicts. Could you fix it @{{author}}?
          🙏"
      label:
        add:
          - conflict
