pull_request_rules:
  - name: Automatic merge for Konflux PRs when build passes
    conditions:
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - -draft
      - -title~=(WIP|wip)
      - -conflict
      - base=main
      - check-success=pre-commit
      - check-success=code_coverage
      - check-success=npm_audit
      - check-success=npm_audit_chatbot
      - check-success=pip_audit
      - check-success=pip_compile
      - check-success=pyright
      - or:
        - check-success~=^ansible-ai-connect-service-on-pr-\d+$
        - check-success=build
      # Ensure no conflicts
      - -label~=(do-not-merge|wip|blocked)
    actions:
      merge:
        method: merge
        message: title+body
      delete_head_branch: {}

  - name: Auto-update PR when out of date
    conditions:
      - base=main
      - -draft
      - -conflict
      - "#approved-reviews-by>=1"
    actions:
      update:
        method: merge

  - name: Comment on PR when ready to merge
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=pre-commit
      - check-success=code_coverage
      - check-success=npm_audit
      - check-success=npm_audit_chatbot
      - check-success=pip_audit
      - check-success=pip_compile
      - check-success=pyright
      - or:
        - check-success~=^ansible-ai-connect-service-on-pr-\d+$
        - check-success=build
      - -merged
      - -closed
      - -draft
    actions:
      comment:
        message: |
          All checks have passed! This PR is ready to be merged.

  - name: Request review for Konflux PRs
    conditions:
      - base=main
      - -draft
      - "#approved-reviews-by=0"
      - or:
        - check-success~=^ansible-ai-connect-service-on-pr-\d+$
        - check-success=build
    actions:
      comment:
        message: |
          Konflux build has passed! This PR needs approval before it can be merged.
