repos:
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/ambv/black
  rev: 24.8.0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    language_version: python3
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    language_version: python3
  - id: end-of-file-fixer
    language_version: python3
  - id: check-yaml
    language_version: python3
  - id: debug-statements
    language_version: python3
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args: [--config=.flake8]
    language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
    language_version: python3
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        types_or: [tsx, ts, javascript]
