---
global:
  scrape_interval: "60s"
  evaluation_interval: "60s"

scrape_configs:
  - job_name: uwsgi-workers
    file_sd_configs:
      - files:
          - uwsgi_target_workers.json
        refresh_interval: 5s

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
