# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansiblerequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x61nsiblerequest.proto\x12\x18\x63\x61ikit.runtime.WisdomExt"1\n\x0e\x41nsibleRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ansiblerequest_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _ANSIBLEREQUEST._serialized_start = 50
    _ANSIBLEREQUEST._serialized_end = 99
# @@protoc_insertion_point(module_scope)
