apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gpu-operator-certified.nvidia-gpu-operator: ""
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
spec:
  channel: v22.9
  installPlanApproval: Automatic
  name: gpu-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: gpu-operator-certified.v22.9.1

