# Generated by Django 4.1.3 on 2023-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_terms_accepted",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
