# Generated by Django 4.2.3 on 2023-10-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_rh_user_is_org_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rh_user_is_org_admin",
            field=models.BooleanField(default=False),
        ),
    ]
