# Generated by Django 4.2.14 on 2024-07-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_rh_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplan",
            name="accept_marketing",
            field=models.BooleanField(default=False),
        ),
    ]
