# Generated by Django 4.2.15 on 2024-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userplan_accept_marketing"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(default=None, null=True),
        ),
    ]
