# Generated by Django 4.2.18 on 2025-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_rh_internal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="external_username",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="family_name",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="given_name",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
