# Generated by Django 4.2.18 on 2025-02-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_email_alter_user_external_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="aap_user",
            field=models.BooleanField(default=False),
        ),
    ]
