# Generated by Django 4.2.22 on 2025-08-01 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organization_enable_anonymization"),
        ("users", "0016_user_aap_user"),
    ]

    run_before = [("dab_rbac", "__first__")]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="The date/time this resource was created."
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date/time this resource was created."
                    ),
                ),
                ("name", models.CharField(help_text="The name of this resource.", max_length=512)),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="The team description."),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The list of admins for this team",
                        related_name="teams_administered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization of this team.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="organizations.organization",
                    ),
                ),
                (
                    "team_parents",
                    models.ManyToManyField(
                        blank=True, related_name="team_children", to="users.team"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The list of users on this team",
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
