# Generated by Django makemigrations after removing Team.admins, Team.users, and Team.team_parents

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_user_options_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="admins",
        ),
        migrations.RemoveField(
            model_name="team",
            name="team_parents",
        ),
        migrations.RemoveField(
            model_name="team",
            name="users",
        ),
    ]
