# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import producer_types_pb2 as producer__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61tegory-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x14producer-types.proto\"h\n\x08\x43\x61tegory\x12\x0e\n\x06labels\x18\x01 \x03(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12=\n\x0b\x65xplanation\x18\x03 \x03(\x0b\x32(.watson_core_data_model.nlp.RelevantText\"\x1c\n\x0cRelevantText\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x90\x01\n\x14\x43\x61tegoriesPrediction\x12\x38\n\ncategories\x18\x01 \x03(\x0b\x32$.watson_core_data_model.nlp.Category\x12>\n\x0bproducer_id\x18\x02 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'category_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _CATEGORY._serialized_start=74
  _CATEGORY._serialized_end=178
  _RELEVANTTEXT._serialized_start=180
  _RELEVANTTEXT._serialized_end=208
  _CATEGORIESPREDICTION._serialized_start=211
  _CATEGORIESPREDICTION._serialized_end=355
# @@protoc_insertion_point(module_scope)
