# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clustering-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import producer_types_pb2 as producer__types__pb2
from . import matrix_types_pb2 as matrix__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63lustering-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x14producer-types.proto\x1a\x12matrix-types.proto\"\xa3\x01\n\x14\x43lusteringPrediction\x12\x13\n\x0b\x63luster_ids\x18\x01 \x03(\x05\x12\x36\n\x05\x63osts\x18\x02 \x01(\x0b\x32\'.watson_core_data_model.nlp.DenseMatrix\x12>\n\x0bproducer_id\x18\x03 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clustering_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _CLUSTERINGPREDICTION._serialized_start=97
  _CLUSTERINGPREDICTION._serialized_end=260
# @@protoc_insertion_point(module_scope)
