# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: codegenerationtaskrequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63odegenerationtaskrequest.proto\x12\x18\x63\x61ikit.runtime.WisdomExt\"]\n\x19\x43odeGenerationTaskRequest\x12\x13\n\x06prompt\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ontext\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_promptB\n\n\x08_contextb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codegenerationtaskrequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CODEGENERATIONTASKREQUEST._serialized_start=61
  _CODEGENERATIONTASKREQUEST._serialized_end=154
# @@protoc_insertion_point(module_scope)
