# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common-service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import producer_types_pb2 as producer__types__pb2
from . import generation_pb2 as generation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ommon-service.proto\x12\x1cwatson.runtime.wisdom_ext.v0\x1a\x14producer-types.proto\x1a\x10generation.proto\"R\n\x0e\x41nsibleRequest\x12\x13\n\x06prompt\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ontext\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_promptB\n\n\x08_context2\x88\x01\n\x10WisdomExtService\x12t\n\x0e\x41nsiblePredict\x12,.watson.runtime.wisdom_ext.v0.AnsibleRequest\x1a\x32.watson_core_data_model.watson_nlp.GeneratedResult\"\x00\x42\x65\n!com.ibm.watson.runtime.wisdom_extP\x01Z>github.ibm.com/ai-foundation/wisdom_ext_runtime_client/runtimeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.ibm.watson.runtime.wisdom_extP\001Z>github.ibm.com/ai-foundation/wisdom_ext_runtime_client/runtime'
  _ANSIBLEREQUEST._serialized_start=94
  _ANSIBLEREQUEST._serialized_end=176
  _WISDOMEXTSERVICE._serialized_start=179
  _WISDOMEXTSERVICE._serialized_end=315
# @@protoc_insertion_point(module_scope)
