# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import producer_types_pb2 as producer__types__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x64\x61ta_model.proto\x12\x35watson_core_data_model.watson_core_ansible_wisdom_ext\x1a\x14producer-types.proto\"[\n\x0bRawDocument\x12\x0c\n\x04text\x18\x01 \x01(\t\x12>\n\x0bproducer_id\x18\x02 \x01(\x0b\x32).watson_core_data_model.common.ProducerId\"|\n\x1c\x41nsibleWisdomModelPrediction\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12>\n\x0bproducer_id\x18\x03 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdB\x7f\n\x17\x63om.ibm.watson.runtime.P\x01Zbgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/watson_core_ansible_wisdom_extb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001Zbgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/watson_core_ansible_wisdom_ext'
    _RAWDOCUMENT._serialized_start = 97
    _RAWDOCUMENT._serialized_end = 188
    _ANSIBLEWISDOMMODELPREDICTION._serialized_start = 190
    _ANSIBLEWISDOMMODELPREDICTION._serialized_end = 314
# @@protoc_insertion_point(module_scope)
