# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import matrix_types_pb2 as matrix__types__pb2
from . import producer_types_pb2 as producer__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65mbedding-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x12matrix-types.proto\x1a\x14producer-types.proto\"\xa6\x02\n\tEmbedding\x12\x35\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\'.watson_core_data_model.nlp.DenseMatrix\x12K\n\x0cvocab_to_idx\x18\x02 \x03(\x0b\x32\x35.watson_core_data_model.nlp.Embedding.VocabToIdxEntry\x12>\n\x0bproducer_id\x18\x03 \x01(\x0b\x32).watson_core_data_model.common.ProducerId\x12\x10\n\x08pad_word\x18\x04 \x01(\t\x12\x10\n\x08unk_word\x18\x05 \x01(\t\x1a\x31\n\x0fVocabToIdxEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\x9d\x01\n\x13\x45mbeddingPrediction\x12\x35\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\'.watson_core_data_model.nlp.DenseMatrix\x12\x0f\n\x07offsets\x18\x02 \x03(\r\x12>\n\x0bproducer_id\x18\x03 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _EMBEDDING_VOCABTOIDXENTRY._options = None
  _EMBEDDING_VOCABTOIDXENTRY._serialized_options = b'8\001'
  _EMBEDDING._serialized_start=96
  _EMBEDDING._serialized_end=390
  _EMBEDDING_VOCABTOIDXENTRY._serialized_start=341
  _EMBEDDING_VOCABTOIDXENTRY._serialized_end=390
  _EMBEDDINGPREDICTION._serialized_start=393
  _EMBEDDINGPREDICTION._serialized_end=550
# @@protoc_insertion_point(module_scope)
