# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emotion-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import producer_types_pb2 as producer__types__pb2
from . import text_primitive_types_pb2 as text__primitive__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65motion-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x14producer-types.proto\x1a\x1atext-primitive-types.proto\"U\n\x07\x45motion\x12\r\n\x05\x61nger\x18\x01 \x01(\x02\x12\x0f\n\x07\x64isgust\x18\x02 \x01(\x02\x12\x0c\n\x04\x66\x65\x61r\x18\x03 \x01(\x02\x12\x0b\n\x03joy\x18\x04 \x01(\x02\x12\x0f\n\x07sadness\x18\x05 \x01(\x02\"v\n\x0e\x45motionMention\x12.\n\x04span\x18\x01 \x01(\x0b\x32 .watson_core_data_model.nlp.Span\x12\x34\n\x07\x65motion\x18\x02 \x01(\x0b\x32#.watson_core_data_model.nlp.Emotion\"\xa9\x01\n\x1b\x41ggregatedEmotionPrediction\x12\x34\n\x07\x65motion\x18\x01 \x01(\x0b\x32#.watson_core_data_model.nlp.Emotion\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x44\n\x10\x65motion_mentions\x18\x03 \x03(\x0b\x32*.watson_core_data_model.nlp.EmotionMention\"\xa9\x01\n\x11\x45motionPrediction\x12T\n\x13\x65motion_predictions\x18\x01 \x03(\x0b\x32\x37.watson_core_data_model.nlp.AggregatedEmotionPrediction\x12>\n\x0bproducer_id\x18\x02 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotion_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _EMOTION._serialized_start=101
  _EMOTION._serialized_end=186
  _EMOTIONMENTION._serialized_start=188
  _EMOTIONMENTION._serialized_end=306
  _AGGREGATEDEMOTIONPREDICTION._serialized_start=309
  _AGGREGATEDEMOTIONPREDICTION._serialized_end=478
  _EMOTIONPREDICTION._serialized_start=481
  _EMOTIONPREDICTION._serialized_end=650
# @@protoc_insertion_point(module_scope)
