# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generatedresult.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import producerid_pb2 as producerid__pb2
import stopreason_pb2 as stopreason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15generatedresult.proto\x12\x1c\x63\x61ikit_data_model.wisdom_ext\x1a\x10producerid.proto\x1a\x10stopreason.proto\"\xb8\x01\n\x0fGeneratedResult\x12\x1d\n\x15generated_token_count\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12=\n\x0bstop_reason\x18\x03 \x01(\x0e\x32(.caikit_data_model.wisdom_ext.StopReason\x12\x39\n\x0bproducer_id\x18\x04 \x01(\x0b\x32$.caikit_data_model.common.ProducerIdb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generatedresult_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERATEDRESULT._serialized_start=92
  _GENERATEDRESULT._serialized_end=276
# @@protoc_insertion_point(module_scope)
