# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import producer_types_pb2 as producer__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10generation.proto\x12!watson_core_data_model.watson_nlp\x1a\x14producer-types.proto\"\xc2\x01\n\x0fGeneratedResult\x12\x1d\n\x15generated_token_count\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x42\n\x0bstop_reason\x18\x03 \x01(\x0e\x32-.watson_core_data_model.watson_nlp.StopReason\x12>\n\x0bproducer_id\x18\x04 \x01(\x0b\x32).watson_core_data_model.common.ProducerId*o\n\nStopReason\x12\x10\n\x0cNOT_FINISHED\x10\x00\x12\x0e\n\nMAX_TOKENS\x10\x01\x12\r\n\tEOS_TOKEN\x10\x02\x12\r\n\tCANCELLED\x10\x03\x12\x0e\n\nTIME_LIMIT\x10\x04\x12\x11\n\rSTOP_SEQUENCE\x10\x05\x42\x7f\n!com.ibm.watson.runtime.wisdom_extP\x01ZXgithub.ibm.com/ai-foundation/wisdom_ext_runtime_client/watson_core_data_model/watson_nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.ibm.watson.runtime.wisdom_extP\001ZXgithub.ibm.com/ai-foundation/wisdom_ext_runtime_client/watson_core_data_model/watson_nlp'
  _STOPREASON._serialized_start=274
  _STOPREASON._serialized_end=385
  _GENERATEDRESULT._serialized_start=78
  _GENERATEDRESULT._serialized_end=272
# @@protoc_insertion_point(module_scope)
