# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyword-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import producer_types_pb2 as producer__types__pb2
from . import text_primitive_types_pb2 as text__primitive__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13keyword-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x14producer-types.proto\x1a\x1atext-primitive-types.proto\"m\n\x07Keyword\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\trelevance\x18\x02 \x01(\x02\x12\x32\n\x08mentions\x18\x03 \x03(\x0b\x32 .watson_core_data_model.nlp.Span\x12\r\n\x05\x63ount\x18\x04 \x01(\r\"\x8b\x01\n\x12KeywordsPrediction\x12\x35\n\x08keywords\x18\x01 \x03(\x0b\x32#.watson_core_data_model.nlp.Keyword\x12>\n\x0bproducer_id\x18\x02 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyword_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _KEYWORD._serialized_start=101
  _KEYWORD._serialized_end=210
  _KEYWORDSPREDICTION._serialized_start=213
  _KEYWORDSPREDICTION._serialized_end=352
# @@protoc_insertion_point(module_scope)
