# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12matrix-types.proto\x12\x1awatson_core_data_model.nlp\"F\n\x0b\x44\x65nseMatrix\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x0c\n\x04rows\x18\x02 \x01(\r\x12\x0c\n\x04\x63ols\x18\x03 \x01(\r\x12\r\n\x05\x64type\x18\x04 \x01(\t\"h\n\x0cSparseMatrix\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x0f\n\x07indices\x18\x02 \x03(\r\x12\x0e\n\x06indptr\x18\x03 \x03(\r\x12\x0c\n\x04rows\x18\x04 \x01(\r\x12\x0c\n\x04\x63ols\x18\x05 \x01(\r\x12\r\n\x05\x64type\x18\x06 \x01(\tBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _DENSEMATRIX._serialized_start=50
  _DENSEMATRIX._serialized_end=120
  _SPARSEMATRIX._serialized_start=122
  _SPARSEMATRIX._serialized_end=226
# @@protoc_insertion_point(module_scope)
