# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relation-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import entity_types_pb2 as entity__types__pb2
from . import producer_types_pb2 as producer__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14relation-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x12\x65ntity-types.proto\x1a\x14producer-types.proto\"\x8c\x02\n\x0fRelationMention\x12\x0c\n\x04type\x18\x01 \x01(\t\x12;\n\x08mention1\x18\x02 \x01(\x0b\x32).watson_core_data_model.nlp.EntityMention\x12;\n\x08mention2\x18\x03 \x01(\x0b\x32).watson_core_data_model.nlp.EntityMention\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12>\n\x0bproducer_id\x18\x05 \x01(\x0b\x32).watson_core_data_model.common.ProducerId\x12\x0f\n\x07subtype\x18\x06 \x01(\t\x12\x0c\n\x04text\x18\x07 \x01(\t\"\xa4\x01\n\x1aRelationMentionsPrediction\x12\x46\n\x11relation_mentions\x18\x01 \x03(\x0b\x32+.watson_core_data_model.nlp.RelationMention\x12>\n\x0bproducer_id\x18\x02 \x01(\x0b\x32).watson_core_data_model.common.ProducerId\"\xde\x01\n\x08Relation\x12\x33\n\x07\x65ntity1\x18\x01 \x01(\x0b\x32\".watson_core_data_model.nlp.Entity\x12\x33\n\x07\x65ntity2\x18\x02 \x01(\x0b\x32\".watson_core_data_model.nlp.Entity\x12\x46\n\x11relation_mentions\x18\x03 \x03(\x0b\x32+.watson_core_data_model.nlp.RelationMention\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\"\x8e\x01\n\x13RelationsPrediction\x12\x37\n\trelations\x18\x01 \x03(\x0b\x32$.watson_core_data_model.nlp.Relation\x12>\n\x0bproducer_id\x18\x02 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relation_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _RELATIONMENTION._serialized_start=95
  _RELATIONMENTION._serialized_end=363
  _RELATIONMENTIONSPREDICTION._serialized_start=366
  _RELATIONMENTIONSPREDICTION._serialized_end=530
  _RELATION._serialized_start=533
  _RELATION._serialized_end=755
  _RELATIONSPREDICTION._serialized_start=758
  _RELATIONSPREDICTION._serialized_end=900
# @@protoc_insertion_point(module_scope)
