# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text-similarity-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import producer_types_pb2 as producer__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btext-similarity-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x14producer-types.proto\"j\n\x18TextSimilarityPrediction\x12\x0e\n\x06scores\x18\x01 \x03(\x02\x12>\n\x0bproducer_id\x18\x02 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_similarity_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _TEXTSIMILARITYPREDICTION._serialized_start=81
  _TEXTSIMILARITYPREDICTION._serialized_end=187
# @@protoc_insertion_point(module_scope)
