# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topic-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import producer_types_pb2 as producer__types__pb2
from . import text_primitive_types_pb2 as text__primitive__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11topic-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x14producer-types.proto\x1a\x1atext-primitive-types.proto\"\x9c\x02\n\x05Topic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0c\n\x04size\x18\x03 \x01(\r\x12\x31\n\x06ngrams\x18\x04 \x03(\x0b\x32!.watson_core_data_model.nlp.NGram\x12\x39\n\x08snippets\x18\x05 \x03(\x0b\x32\'.watson_core_data_model.nlp.TopicPhrase\x12:\n\tsentences\x18\x06 \x03(\x0b\x32\'.watson_core_data_model.nlp.TopicPhrase\x12>\n\x0bproducer_id\x18\x07 \x01(\x0b\x32).watson_core_data_model.common.ProducerId\"-\n\x0bTopicPhrase\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\"E\n\x10TopicsPrediction\x12\x31\n\x06topics\x18\x01 \x03(\x0b\x32!.watson_core_data_model.nlp.TopicBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'topic_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _TOPIC._serialized_start=100
  _TOPIC._serialized_end=384
  _TOPICPHRASE._serialized_start=386
  _TOPICPHRASE._serialized_end=431
  _TOPICSPREDICTION._serialized_start=433
  _TOPICSPREDICTION._serialized_end=502
# @@protoc_insertion_point(module_scope)
