# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import traininginforequest_pb2 as traininginforequest__pb2
import traininginforesponse_pb2 as traininginforesponse__pb2


class TrainingManagementStub(object):
    """-- SERVICES ----------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrainingStatus = channel.unary_unary(
                '/caikit.runtime.training.TrainingManagement/GetTrainingStatus',
                request_serializer=traininginforequest__pb2.TrainingInfoRequest.SerializeToString,
                response_deserializer=traininginforesponse__pb2.TrainingInfoResponse.FromString,
                )


class TrainingManagementServicer(object):
    """-- SERVICES ----------------------------------------------------------------

    """

    def GetTrainingStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStatus,
                    request_deserializer=traininginforequest__pb2.TrainingInfoRequest.FromString,
                    response_serializer=traininginforesponse__pb2.TrainingInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'caikit.runtime.training.TrainingManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainingManagement(object):
    """-- SERVICES ----------------------------------------------------------------

    """

    @staticmethod
    def GetTrainingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/caikit.runtime.training.TrainingManagement/GetTrainingStatus',
            traininginforequest__pb2.TrainingInfoRequest.SerializeToString,
            traininginforesponse__pb2.TrainingInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
