# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traininginforesponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trainingstatus_pb2 as trainingstatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atraininginforesponse.proto\x12\x19\x63\x61ikit_data_model.runtime\x1a\x14trainingstatus.proto\"\xb6\x01\n\x14TrainingInfoResponse\x12\x13\n\x0btraining_id\x18\x01 \x01(\t\x12\x39\n\x06status\x18\x02 \x01(\x0e\x32).caikit_data_model.runtime.TrainingStatus\x12\x1c\n\x14submission_timestamp\x18\x03 \x01(\t\x12\x1c\n\x14\x63ompletion_timestamp\x18\x04 \x01(\t\x12\x12\n\nerror_code\x18\x05 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traininginforesponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAININGINFORESPONSE._serialized_start=80
  _TRAININGINFORESPONSE._serialized_end=262
# @@protoc_insertion_point(module_scope)
