# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trainingstatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14trainingstatus.proto\x12\x19\x63\x61ikit_data_model.runtime*v\n\x0eTrainingStatus\x12\x0f\n\x0bNOT_STARTED\x10\x00\x12\n\n\x06HALTED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x12\x0f\n\x0b\x44OWNLOADING\x10\x03\x12\x0e\n\nPROCESSING\x10\x04\x12\x0b\n\x07STORING\x10\x05\x12\r\n\tCOMPLETED\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trainingstatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAININGSTATUS._serialized_start=51
  _TRAININGSTATUS._serialized_end=169
# @@protoc_insertion_point(module_scope)
