# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trainingmanagement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import traininginforequest_pb2 as traininginforequest__pb2
import traininginforesponse_pb2 as traininginforesponse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18trainingmanagement.proto\x12\x17\x63\x61ikit.runtime.training\x1a\x19traininginforequest.proto\x1a\x1atraininginforesponse.proto2\x8a\x01\n\x12TrainingManagement\x12t\n\x11GetTrainingStatus\x12..caikit_data_model.runtime.TrainingInfoRequest\x1a/.caikit_data_model.runtime.TrainingInfoResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trainingmanagement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAININGMANAGEMENT._serialized_start=109
  _TRAININGMANAGEMENT._serialized_end=247
# @@protoc_insertion_point(module_scope)
