# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorization-types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import matrix_types_pb2 as matrix__types__pb2
from . import producer_types_pb2 as producer__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19vectorization-types.proto\x12\x1awatson_core_data_model.nlp\x1a\x12matrix-types.proto\x1a\x14producer-types.proto\"\x8b\x02\n\rVectorization\x12\x36\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32(.watson_core_data_model.nlp.SparseMatrix\x12O\n\x0cvocab_to_idx\x18\x02 \x03(\x0b\x32\x39.watson_core_data_model.nlp.Vectorization.VocabToIdxEntry\x12>\n\x0bproducer_id\x18\x03 \x01(\x0b\x32).watson_core_data_model.common.ProducerId\x1a\x31\n\x0fVocabToIdxEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\x91\x01\n\x17VectorizationPrediction\x12\x36\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32(.watson_core_data_model.nlp.SparseMatrix\x12>\n\x0bproducer_id\x18\x02 \x01(\x0b\x32).watson_core_data_model.common.ProducerIdBd\n\x17\x63om.ibm.watson.runtime.P\x01ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectorization_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ibm.watson.runtime.P\001ZGgithub.ibm.com/ai-foundation/_runtime_client/watson_core_data_model/nlp'
  _VECTORIZATION_VOCABTOIDXENTRY._options = None
  _VECTORIZATION_VOCABTOIDXENTRY._serialized_options = b'8\001'
  _VECTORIZATION._serialized_start=100
  _VECTORIZATION._serialized_end=367
  _VECTORIZATION_VOCABTOIDXENTRY._serialized_start=318
  _VECTORIZATION_VOCABTOIDXENTRY._serialized_end=367
  _VECTORIZATIONPREDICTION._serialized_start=370
  _VECTORIZATIONPREDICTION._serialized_end=515
# @@protoc_insertion_point(module_scope)
