# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import codegenerationtaskansiblecodegentrainrequest_pb2 as codegenerationtaskansiblecodegentrainrequest__pb2
import trainingjob_pb2 as trainingjob__pb2


class WisdomExtTrainingServiceStub(object):
    """-- SERVICES ----------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CodeGenerationTaskAnsibleCodegenTrain = channel.unary_unary(
                '/caikit.runtime.WisdomExt.WisdomExtTrainingService/CodeGenerationTaskAnsibleCodegenTrain',
                request_serializer=codegenerationtaskansiblecodegentrainrequest__pb2.CodeGenerationTaskAnsibleCodegenTrainRequest.SerializeToString,
                response_deserializer=trainingjob__pb2.TrainingJob.FromString,
                )


class WisdomExtTrainingServiceServicer(object):
    """-- SERVICES ----------------------------------------------------------------

    """

    def CodeGenerationTaskAnsibleCodegenTrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WisdomExtTrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CodeGenerationTaskAnsibleCodegenTrain': grpc.unary_unary_rpc_method_handler(
                    servicer.CodeGenerationTaskAnsibleCodegenTrain,
                    request_deserializer=codegenerationtaskansiblecodegentrainrequest__pb2.CodeGenerationTaskAnsibleCodegenTrainRequest.FromString,
                    response_serializer=trainingjob__pb2.TrainingJob.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'caikit.runtime.WisdomExt.WisdomExtTrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WisdomExtTrainingService(object):
    """-- SERVICES ----------------------------------------------------------------

    """

    @staticmethod
    def CodeGenerationTaskAnsibleCodegenTrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/caikit.runtime.WisdomExt.WisdomExtTrainingService/CodeGenerationTaskAnsibleCodegenTrain',
            codegenerationtaskansiblecodegentrainrequest__pb2.CodeGenerationTaskAnsibleCodegenTrainRequest.SerializeToString,
            trainingjob__pb2.TrainingJob.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
