# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wisdomexttrainingservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import codegenerationtaskansiblecodegentrainrequest_pb2 as codegenerationtaskansiblecodegentrainrequest__pb2
import trainingjob_pb2 as trainingjob__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ewisdomexttrainingservice.proto\x12\x18\x63\x61ikit.runtime.WisdomExt\x1a\x32\x63odegenerationtaskansiblecodegentrainrequest.proto\x1a\x11trainingjob.proto2\xb4\x01\n\x18WisdomExtTrainingService\x12\x97\x01\n%CodeGenerationTaskAnsibleCodegenTrain\x12\x46.caikit.runtime.WisdomExt.CodeGenerationTaskAnsibleCodegenTrainRequest\x1a&.caikit_data_model.runtime.TrainingJobb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wisdomexttrainingservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WISDOMEXTTRAININGSERVICE._serialized_start=132
  _WISDOMEXTTRAININGSERVICE._serialized_end=312
# @@protoc_insertion_point(module_scope)
