# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wisdomextservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import codegenerationtaskrequest_pb2 as codegenerationtaskrequest__pb2
import generatedresult_pb2 as generatedresult__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16wisdomextservice.proto\x12\x18\x63\x61ikit.runtime.WisdomExt\x1a\x1f\x63odegenerationtaskrequest.proto\x1a\x15generatedresult.proto2\x93\x01\n\x10WisdomExtService\x12\x7f\n\x19\x43odeGenerationTaskPredict\x12\x33.caikit.runtime.WisdomExt.CodeGenerationTaskRequest\x1a-.caikit_data_model.wisdom_ext.GeneratedResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wisdomextservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WISDOMEXTSERVICE._serialized_start=109
  _WISDOMEXTSERVICE._serialized_end=256
# @@protoc_insertion_point(module_scope)
