# Generated by Django 4.2.1 on 2023-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_split_terms_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
