# Generated by Django 4.2.7 on 2023-12-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_external_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="RHOrganization",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("telemetry_opt_out", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="rhorganization",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.rhorganization",
            ),
        ),
    ]
