# Generated by Django 4.1.3 on 2023-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'model_mesh_api_type',
                    models.CharField(
                        choices=[('grpc', 'gRPC'), ('http', 'HTTP')], default='http', max_length=4
                    ),
                ),
                ('inference_url', models.TextField()),
                ('management_url', models.TextField()),
            ],
        ),
    ]
