# Generated by Django 4.2.3 on 2023-11-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("telemetry_opt_out", models.BooleanField(default=False)),
            ],
        ),
    ]
