# Generated by Django 4.2.11 on 2024-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_user_organization_fix_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="telemetry_opt_out",
        ),
        migrations.AddField(
            model_name="organization",
            name="_telemetry_opt_out",
            field=models.BooleanField(db_column="telemetry_opt_out", default=False),
        ),
    ]
