# Generated by Django 4.2.20 on 2025-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_organization_telemetry_opt_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalorganization",
            name="enable_anonymization",
            field=models.BooleanField(default=True),
        ),
    ]
