ALLOW_LIST = {
    'attribution': {
        'suggestionId': None,
        'duration': None,
        'encode_duration': None,
        'search_duration': None,
        'attributions': {
            'ansible_type': None,
            'score': None,
        },
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'completion': {
        'duration': None,
        'request': {
            'prompt': None,
            'context': None,
        },
        'response': {
            'exception': None,
            'error_type': None,
            'message': None,
            'predictions': None,
            'status_code': None,
            'status_text': None,
        },
        'suggestionId': None,
        'metadata': {
            'documentUri': None,
            'activityId': None,
        },
        'modelName': None,
        'imageTags': None,
        'tasks': None,
        'tasksCount': None,
        'promptType': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'prediction': {
        'duration': None,
        'exception': None,
        'problem': None,
        'request': {
            'prompt': None,
            'context': None,
            'userId': None,
            'rh_user_has_seat': None,
            'rh_user_org_id': None,
            'suggestionId': None,
        },
        'response': {},
        'suggestionId': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'postprocessLint': {
        'exception': None,
        'problem': None,
        'duration': None,
        'recommendation': None,
        'postprocessed': None,
        'suggestionId': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'postprocess': {
        'exception': None,
        'problem': None,
        'duration': None,
        'recommendation': None,
        'truncated': None,
        'postprocessed': None,
        'details': None,
        'suggestionId': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'inlineSuggestionFeedback': {
        'action': None,
        'activityId': None,
        'exception': None,
        'latency': None,
        'suggestionId': None,
        'userActionTime': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'segmentError': {
        'error_type': None,
        'details': None,
        'timestamp': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
    },
    'sentimentFeedback': {
        'value': None,
        'feedback': None,
        'exception': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'ansibleContentFeedback': {
        'content': None,
        'documentUri': None,
        'trigger': None,
        'activityId': None,
        'exception': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'suggestionQualityFeedback': {
        'prompt': None,
        'providedSuggestion': None,
        'expectedSuggestion': None,
        'additionalComment': None,
        'exception': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
    'issueFeedback': {
        'title': None,
        'description': None,
        'type': None,
        'exception': None,
        'modelName': None,
        'imageTags': None,
        'hostname': None,
        'groups': None,
        'rh_user_has_seat': None,
        'rh_user_org_id': None,
        'timestamp': None,
    },
}
