---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wisdom
    app.kubernetes.io/component: wisdom
    app.kubernetes.io/instance: wisdom
  name: wisdom
  namespace: wisdom-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: wisdom
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wisdom
    spec:
      containers:
      - image: $CONTAINER_IMAGE
        imagePullPolicy: IfNotPresent
        name: wisdom
        ports:
        - containerPort: 7070
          protocol: TCP
        - containerPort: 7071
          protocol: TCP
        - containerPort: 7080
          protocol: TCP
        - containerPort: 7081
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8082
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wisdom
    app.kubernetes.io/component: wisdom
    app.kubernetes.io/instance: wisdom
  name: wisdom
  namespace: wisdom-dev
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 7070-tcp
    port: 7070
    protocol: TCP
    targetPort: 7070
  - name: 7071-tcp
    port: 7071
    protocol: TCP
    targetPort: 7071
  - name: 7080-tcp
    port: 7080
    protocol: TCP
    targetPort: 7080
  - name: 7081-tcp
    port: 7081
    protocol: TCP
    targetPort: 7081
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: 8082-tcp
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    deployment: wisdom
  sessionAffinity: None
  type: ClusterIP
