name: Monitor repo for security vulnerabilities
on:
  push:
    branches:
      - 'main'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.12'
      - uses: snyk/actions/setup@11b673cfb4b0dc0d860a1323caa199d54950dcce # master
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Monitor project and report vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --all-projects --skip-unresolved

      - name: Generate code vulnerability report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --project-name="ansible/ansible-ai-connect-service" --report ${{ github.workspace }}
        continue-on-error: true
